package com.gruppotesi.foosball.client;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.ClickListener;
import com.google.gwt.user.client.ui.DockPanel;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.RootPanel;
import com.google.gwt.user.client.ui.Widget;
import com.google.gwt.user.client.ui.TabPanel;


/**
 * Entry point classes define <code>onModuleLoad()</code>.
 */
public class Foosball implements EntryPoint
{ 

	// Composites that encapsulate CSS, RPC and History demo
	private LoginRPC loginRPC = new LoginRPC();

	// Foosball functionality generated by applicationCreator.cmd script
	final Label label = new Label();
    final Button button = new Button("Foosball");
 
    
  /**
   * This is the entry point method.
   */
  public void onModuleLoad() 
  {
    // button inline event listener
    button.addClickListener(new ClickListener() 
    {
      public void onClick(Widget sender) 
      {
        if (label.getText().equals(""))
        {
           label.setText("Foosball World!");
        }
        else
        {
           label.setText("");
        }
      }
    });

    // add panel and other controls to the window
    RootPanel slot = RootPanel.get();    
    
    DockPanel dock = new DockPanel();
    if (slot != null) 
    {
      dock.add(label, DockPanel.WEST);
      
      dock.add(button, DockPanel.CENTER);
      
      dock.add(loginRPC, DockPanel.SOUTH);
      
      slot.add(dock);
    }
  }
}
